name: Pr Checker

on: [pull_request, pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Playwright
        run: npm install playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      
      - run: yarn playwright install   
      - run: yarn install --frozen-lockfile
      - run: yarn build
